---

- name: Install openntpd
  apt:
    name: "{{ openntpd_package }}"
    state: present

- name: Create /etc/default/openntpd
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ openntpd_service }}"
    validate: sh -n %s
  register: __register_openntpd_flags
  notify:
    - Restart openntpd

- name: Enable openntpd
  service:
    name: "{{ openntpd_service }}"
    enabled: yes
