---
# tasks file for ansible-role-openntpd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create ntpd.conf
  template:
    src: ntpd.conf.j2
    dest: "{{ openntpd_conf_file }}"
    validate: "{{ openntpd_bin }} -n -f %s"
  register: __register_openntpd_ntpd_conf
  notify: Restart openntpd

- name: Start openntpd
  service:
    name: "{{ openntpd_service }}"
    state: started

- name: Restart openntpd at the end of the role
  service:
    name: "{{ openntpd_service }}"
    state: restarted
  when:
    - __register_openntpd_ntpd_conf.changed or __register_openntpd_flags.changed
